import { Link } from 'react-router-dom';
import { Icon } from '../../components/Icon';
import { curriculum } from '../../lessons/curriculum';
import TopologyEditor from '../../components/TopologyEditor/TopologyEditor';
import { lab } from '../../application/LabController';
import { useUI } from '../../stores/ui';

export default function HomePage() {
  useUI(s => s.revision);
  const done = curriculum.filter(c => lab.completed.has(`${c.id}-mastery`)).length;
  return <div className="home-page"><div className="welcome-line"><span>YOUR NEXT CONNECTION</span><span><span className="status-dot"/> 学びを、実践につなげよう</span></div>
    <section className="home-hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> HANDS-ON NETWORK LEARNING</div><h1>「つながる」を、<br/><span>自分の言葉で。</span></h1><p>パケットの動きを目で見て、自分でネットワークを組み立てる。<br/>覚えた知識を、設計と障害調査で使える力に。</p><div className="hero-actions"><Link className="button" to="/learn/tcp-ip">学習をはじめる<Icon name="arrow" size={18}/></Link><Link className="hero-text-link" to="/simulator"><Icon name="play" size={15}/>まずは触ってみる</Link></div><div className="hero-footnote"><span><Icon name="check" size={13}/>インストール不要</span><span><Icon name="check" size={13}/>失敗できる実験環境</span><span><Icon name="check" size={13}/>自分のペースで</span></div></div>
      <div className="hero-visual" aria-label="送信元からルータを経由して宛先へ届くパケットの模式図"><div className="hero-grid"/><div className="hero-visual-title"><span className="status-dot"/> A PACKET'S JOURNEY<span>01 — 04</span></div><div className="hero-path"><div className="hero-endpoint"><div className="hero-device"><Icon name="pc" size={32}/></div><strong>YOU</strong><small>192.168.1.10</small></div><div className="hero-wire"><span className="travelling-packet"><Icon name="packet" size={16}/></span><span className="wire-label">Ethernet</span></div><div className="hero-endpoint"><div className="hero-device router"><Icon name="router" size={34}/></div><strong>ROUTER</strong><small>Find the next hop</small></div><div className="hero-wire second"><span className="wire-label">IPv4</span></div><div className="hero-endpoint"><div className="hero-device"><Icon name="globe" size={32}/></div><strong>THE WORLD</strong><small>One hop at a time</small></div></div><div className="hero-packet-card"><span className="packet-card-icon"><Icon name="layers" size={21}/></span><div><strong>小さなパケットに、大きな仕組み。</strong><span>Ethernet <i>→</i> IPv4 <i>→</i> ICMP</span></div><span className="packet-card-status">EXPLORE</span></div><div className="hero-visual-bottom">LOOK INSIDE THE NETWORK<span>↗</span></div></div>
    </section>
    <div className="learning-stats"><div><span className="stat-icon"><Icon name="book"/></span><p><strong>12<span>chapters</span></strong><small>基礎から実務へのロードマップ</small></p></div><div><span className="stat-icon"><Icon name="lab"/></span><p><strong>4<span>workspaces</span></strong><small>Network・AWS・Terraform・Packet Analyzer</small></p></div><div><span className="stat-icon"><Icon name="target"/></span><p><strong>{done}<span>/ {curriculum.length} simulations</span></strong><small>読むだけでなく、組み立てられるまで</small></p></div></div>
    <section className="featured-lab"><div className="section-heading"><div><span className="eyebrow">LEARN BY DOING</span><h2>つなぐ。壊す。直して、わかる。</h2></div><Link to="/lab/routing-01">実践ラボを開く<Icon name="arrow" size={17}/></Link></div><div className="lab-feature-card"><div className="lab-feature-info"><span className="tag">GUIDED LAB <span>03.01</span></span><h3>ふたつのLANを、<br/>静的ルートでつなぐ。</h3><p>PC1からPC2へ、pingは届く？<br/>経路表とパケットを手がかりに、<br/>通信の行きと帰りをつくろう。</p><div className="lab-meta"><span><Icon name="clock" size={14}/>約25分</span><span>初級 → 実践</span></div><Link className="button" to="/lab/routing-01">ラボをはじめる<Icon name="arrow" size={16}/></Link></div><div className="lab-feature-topology"><TopologyEditor compact/><div className="feature-caption"><span><Icon name="bulb" size={15}/>現在のラボ構成を表示しています</span><code>PC1 &gt; ping 192.168.2.10</code></div></div></div></section>
    <section className="learning-section"><div className="section-heading"><div><span className="eyebrow">BUILD YOUR FOUNDATION</span><h2>仕組みから、一歩ずつ。</h2></div><Link to="/roadmap">学習の全体像<Icon name="arrow" size={17}/></Link></div><div className="lesson-cards">{[
      { id: 'tcp-ip', n: '01', title: '通信の中を、のぞいてみる。', subtitle: 'TCP / IPのきほん', text: 'レイヤーとカプセル化を理解して、パケットが進む道を追ってみよう。', icon: 'layers' as const, color: 'mint' },
      { id: 'subnet', n: '02', title: 'アドレスには、意味がある。', subtitle: 'IPアドレスとサブネット', text: 'ビットを見ながら、ネットワーク部とホスト部の境界をつかもう。', icon: 'globe' as const, color: 'peach' },
      { id: 'routing', n: '03', title: '次の一歩を、決める。', subtitle: 'ルーティング', text: 'パケットはどこへ向かう？ 経路表を読み、ふたつのLANをつなごう。', icon: 'network' as const, color: 'blue' },
    ].map(c => <Link key={c.id} to={`/learn/${c.id}`} className="lesson-card"><div className="lesson-card-top"><span className={`lesson-icon ${c.color}`}><Icon name={c.icon} size={25}/></span><span>CHAPTER {c.n}</span></div><span className="lesson-card-subtitle">{c.subtitle}</span><h3>{c.title}</h3><p>{c.text}</p><div className="lesson-card-bottom"><span><Icon name="book" size={13}/>Theory → Simulation · {lab.completed.has(`${c.id}-mastery`) ? '完了' : '学習する'}</span><Icon name="arrow" size={20}/></div></Link>)}</div></section>
    <section className="learning-section"><div className="section-heading"><div><span className="eyebrow">AND BEYOND</span><h2>LANから、クラウドとコードまで。</h2></div><Link to="/labs">すべてのラボ<Icon name="arrow" size={17}/></Link></div><ol className="chapter-strip">{curriculum.slice(3).map((c, i) => <li key={c.id}><Link to={`/learn/${c.id}`}><span>{String(i + 4).padStart(2, '0')}</span><strong>{c.title}</strong><small>{lab.completed.has(`${c.id}-mastery`) ? '✓ 完了' : c.subtitle}</small></Link></li>)}</ol></section>
    <section className="philosophy"><span className="quote-mark">“</span><div><h3>覚えるだけでなく、「なぜ」を説明できる人へ。</h3><p>しくみを言葉で理解し（Theory）、同じものを自分の手で1ステップずつ組み立てる（Simulation）。小さな実験を積み重ねて、現場で使える判断力を育てます。</p></div><span className="philosophy-label">THE PATH WAY</span></section>
  </div>;
}
